Update passport.md
LaravelRUS/docs pull request #289
Opened 2023-03-11 18:24 UTC by wapster

Don't recommend legacy Passport grants anymore

2023-03-11 18:35 UTC, SerafimArts requested changes

2023-03-11 18:35 UTC, SerafimArts commented on passport.md
> +> {Примечание} Мы больше не рекомендуем использовать токены для предоставления пароля. Вместо этого вам следует выбрать [тип гаранта, который в настоящее время рекомендуется OAuth2 Server](https://oa
Следует использовать `{tip}`, `{note}` или `{video}`, как в оригинале, без перевода. 

Такие цитаты автоматически обрабатываются и к ним добавляется CSS класс с именем, которое указано в фигурных скобках.

1) Обработчик: https://github.com/LaravelRUS/laravel.su/blob/master/libs/content-renderer/src/Extension/QuotesFormatter.php#L61
2) Сами стили: https://github.com/LaravelRUS/laravel.su/blob/master/resources/css/ui/_blockquote.scss#LL56C13-L56C13

2023-03-11 18:35 UTC, SerafimArts commented on passport.md
> +> {Примечание} Мы больше не рекомендуем использовать токены для предоставления пароля. Вместо этого вам следует выбрать [тип гаранта, который в настоящее время рекомендуется OAuth2 Server](https://oa
same

2023-03-11 18:36 UTC, SerafimArts commented
Поправишь?

2023-03-12 12:30 UTC, wapster commented on passport.md
> +> {Примечание} Мы больше не рекомендуем использовать токены для предоставления пароля. Вместо этого вам следует выбрать [тип гаранта, который в настоящее время рекомендуется OAuth2 Server](https://oa
Спасибо, учту на будущее.

2023-03-12 14:14 UTC, SerafimArts commented on passport.md
> +> {Примечание} Если ваше приложение в основном использует Passport для выдачи токенов личного доступа, рассмотрите возможность использования [Laravel Sanctum](/docs/{{version}}/sanctum), облегченной
Тут тоже осталось, если что. Просто я не стал это помечать уже =)

2023-03-13 16:28 UTC, merged